service: nuxt-app-lamba

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: serverless

functions:
  nuxt:
    handler: ./.output/server/index.handler
    events:
      - httpApi: '*'
    package:
      patterns:
        - .output/server/**

